package com.xenoamess.kaishek.zg361;

import com.xenoamess.kaishek.profile.ScopeType;

import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Hand-authored differential vectors for the offline 014 replay.
 *
 * <p>The expected snapshots are deliberately independent constants rather
 * than values generated by the replay itself.  A mismatch therefore catches
 * regressions in queue ordering, binding invalidation, or receipt accounting.
 * The vectors are synthetic/runtime-fixture evidence only; the provenance
 * fields point at the companion P-script evidence without importing it.</p>
 */
public final class Appeal014DifferentialFixture {
    public static final String FIXTURE_ID = "zg361-014-appeal-replay-v1";
    public static final String READINESS = "runtime-fixture";
    public static final String ACCEPTANCE_SOURCE =
            "mod_zhongguo_style/tools/mechanism_acceptance/acceptance_001_036.json#014";
    public static final String ACCEPTANCE_SOURCE_SHA256 =
            "66987c323fcfac3ecd2bd8dda2671744c8ba142ff3d8ae7b9969b128ec9b4f98";
    public static final String EFFECT_SOURCE =
            "mod_zhongguo_style/common/scripted_effects/zg361_effects.txt#676-804";
    public static final String EFFECT_SOURCE_SHA256 =
            "c08f450dbe3f3deafac35e337c8cb2001a9fdc1830b68d0ca8825e604c795f4c";

    private static final String TREASURY_PATH = "subject_treasury/gold";
    private static final String GOLD_PATH = "subject_personal_gold/gold";
    private static final String MERIT_PATH = "subject_merit/merit";

    private static final Map<String, Long> CHARGED_BALANCES = Map.of(
            TREASURY_PATH, 950L,
            GOLD_PATH, 975L,
            MERIT_PATH, 940L);
    private static final Map<String, Long> RESTORED_BALANCES = Map.of(
            TREASURY_PATH, 1000L,
            GOLD_PATH, 1000L,
            MERIT_PATH, 1000L);
    private static final Map<String, Long> NO_REFUNDS = Map.of(
            Appeal014Replay.TREASURY_RECEIPT, 0L,
            Appeal014Replay.GOLD_RECEIPT, 0L,
            Appeal014Replay.MERIT_RECEIPT, 0L);
    private static final Map<String, Long> FULL_REFUNDS = Map.of(
            Appeal014Replay.TREASURY_RECEIPT, 50L,
            Appeal014Replay.GOLD_RECEIPT, 25L,
            Appeal014Replay.MERIT_RECEIPT, 60L);

    private Appeal014DifferentialFixture() { }

    /** A finite action from the fixture's small replay vocabulary. */
    public record Action(String operation, Long argument) {
        public Action {
            if (operation == null || operation.isBlank()) throw new IllegalArgumentException("operation is blank");
            if (operation.equals("advance") && argument == null) {
                throw new IllegalArgumentException("advance requires an epoch day");
            }
            if (!operation.equals("advance") && argument != null) {
                throw new IllegalArgumentException("only advance accepts an argument");
            }
        }

        public static Action open() { return new Action("open", null); }
        public static Action submit() { return new Action("submit", null); }
        public static Action resolve() { return new Action("resolve", null); }
        public static Action reopen() { return new Action("reopen", null); }
        public static Action revise() { return new Action("revise", null); }
        public static Action advance(long day) { return new Action("advance", day); }
    }

    /** Expected outcome sequence and canonical terminal snapshot. */
    public record Expected(List<Appeal014Replay.Outcome> outcomes,
                           Appeal014Replay.Snapshot snapshot) {
        public Expected {
            outcomes = List.copyOf(Objects.requireNonNull(outcomes, "outcomes"));
            Objects.requireNonNull(snapshot, "snapshot");
        }
    }

    /** One scenario plus its independent expected vector. */
    public record CaseFixture(String id, Appeal014Replay.Scenario scenario,
                              List<Action> actions, Expected expected) {
        public CaseFixture {
            if (id == null || id.isBlank()) throw new IllegalArgumentException("fixture id is blank");
            Objects.requireNonNull(scenario, "scenario");
            actions = List.copyOf(Objects.requireNonNull(actions, "actions"));
            Objects.requireNonNull(expected, "expected");
        }
    }

    /** A normalized comparison result suitable for CI output. */
    public record Comparison(String scenarioId, boolean match, List<String> mismatches) {
        public Comparison {
            if (scenarioId == null || scenarioId.isBlank()) throw new IllegalArgumentException("scenario id is blank");
            mismatches = List.copyOf(Objects.requireNonNull(mismatches, "mismatches"));
            if (match && !mismatches.isEmpty()) throw new IllegalArgumentException("matching comparison has mismatches");
            if (!match && mismatches.isEmpty()) throw new IllegalArgumentException("mismatch comparison has no diagnostics");
        }
    }

    /** Return all independent vectors in stable order. */
    public static List<CaseFixture> cases() {
        return List.of(
                resolvedBeforeDeadline(),
                expiresAtDeadline(),
                staleAfterReopen(),
                staleAfterRevision());
    }

    /** Execute one vector without consulting CK3 or an external corpus. */
    public static Appeal014Replay run(CaseFixture fixture) {
        Objects.requireNonNull(fixture, "fixture");
        Appeal014Replay replay = new Appeal014Replay(fixture.scenario());
        for (Action action : fixture.actions()) {
            switch (action.operation()) {
                case "open" -> replay.open();
                case "submit" -> replay.submit();
                case "resolve" -> replay.resolve();
                case "reopen" -> replay.reopenForFixture();
                case "revise" -> replay.reviseForFixture();
                case "advance" -> replay.advanceTo(action.argument());
                default -> throw new IllegalArgumentException("unknown fixture action: " + action.operation());
            }
        }
        return replay;
    }

    /** Compare replay output with the hand-authored expected vector. */
    public static Comparison compare(CaseFixture fixture) {
        Objects.requireNonNull(fixture, "fixture");
        Appeal014Replay replay = run(fixture);
        List<String> mismatches = new java.util.ArrayList<>();
        List<Appeal014Replay.Outcome> actualOutcomes = replay.history().stream()
                .map(Appeal014Replay.Step::outcome).toList();
        if (!fixture.expected().outcomes().equals(actualOutcomes)) {
            mismatches.add("outcomes expected=" + fixture.expected().outcomes()
                    + " actual=" + actualOutcomes);
        }
        if (!fixture.expected().snapshot().equals(replay.snapshot())) {
            mismatches.add("snapshot expected=" + fixture.expected().snapshot()
                    + " actual=" + replay.snapshot());
        }
        return new Comparison(fixture.id(), mismatches.isEmpty(), mismatches);
    }

    public static Map<String, String> provenance() {
        return Map.of(
                "fixture", FIXTURE_ID,
                "readiness", READINESS,
                "acceptance_source", ACCEPTANCE_SOURCE,
                "acceptance_sha256", ACCEPTANCE_SOURCE_SHA256,
                "effect_source", EFFECT_SOURCE,
                "effect_sha256", EFFECT_SOURCE_SHA256);
    }

    private static Appeal014Replay.Scenario scenario(String id) {
        var owner = new com.xenoamess.kaishek.runtime.ScopeRef(ScopeType.CHARACTER, "owner014");
        var subject = new com.xenoamess.kaishek.runtime.ScopeRef(ScopeType.CHARACTER, "subject014");
        var reviewer = owner;
        return new Appeal014Replay.Scenario(
                id, "appeal-014-" + id, owner, subject, reviewer, 100, 90,
                List.of(
                        new Appeal014Replay.ReceiptSpec(
                                Appeal014Replay.TREASURY_RECEIPT, "subject_treasury", "gold", 50),
                        new Appeal014Replay.ReceiptSpec(
                                Appeal014Replay.GOLD_RECEIPT, "subject_personal_gold", "gold", 25),
                        new Appeal014Replay.ReceiptSpec(
                                Appeal014Replay.MERIT_RECEIPT, "subject_merit", "merit", 60)),
                Map.of(
                        new Appeal014Replay.BalanceKey("subject_treasury", "gold"), 1000L,
                        new Appeal014Replay.BalanceKey("subject_personal_gold", "gold"), 1000L,
                        new Appeal014Replay.BalanceKey("subject_merit", "merit"), 1000L));
    }

    private static CaseFixture resolvedBeforeDeadline() {
        return new CaseFixture(
                "resolved-before-deadline",
                scenario("resolved-before-deadline"),
                List.of(Action.open(), Action.submit(), Action.resolve(), Action.resolve(), Action.advance(190)),
                new Expected(
                        List.of(Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.IDEMPOTENT_NOOP,
                                Appeal014Replay.Outcome.IDEMPOTENT_NOOP),
                        snapshot("resolved-before-deadline", Appeal014Replay.State.RESOLVED,
                                0, 0, 0, 0, 190, 0, RESTORED_BALANCES, FULL_REFUNDS)));
    }

    private static CaseFixture expiresAtDeadline() {
        return new CaseFixture(
                "expires-at-deadline",
                scenario("expires-at-deadline"),
                List.of(Action.open(), Action.submit(), Action.advance(190), Action.resolve()),
                new Expected(
                        List.of(Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.STALE_NOOP),
                        snapshot("expires-at-deadline", Appeal014Replay.State.EXPIRED,
                                0, 0, 0, 0, 190, 0, CHARGED_BALANCES, NO_REFUNDS)));
    }

    private static CaseFixture staleAfterReopen() {
        return new CaseFixture(
                "stale-after-reopen",
                scenario("stale-after-reopen"),
                List.of(Action.open(), Action.submit(), Action.reopen(), Action.advance(190), Action.resolve()),
                new Expected(
                        List.of(Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.STALE_NOOP,
                                Appeal014Replay.Outcome.STALE_DEADLINE_NOOP,
                                Appeal014Replay.Outcome.STALE_NOOP),
                        snapshot("stale-after-reopen", Appeal014Replay.State.APPEAL_OPEN,
                                0, 0, 1, 0, 190, 1, CHARGED_BALANCES, NO_REFUNDS)));
    }

    private static CaseFixture staleAfterRevision() {
        return new CaseFixture(
                "stale-after-revision",
                scenario("stale-after-revision"),
                List.of(Action.open(), Action.submit(), Action.revise(), Action.advance(190), Action.resolve()),
                new Expected(
                        List.of(Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.APPLIED,
                                Appeal014Replay.Outcome.STALE_NOOP,
                                Appeal014Replay.Outcome.STALE_DEADLINE_NOOP,
                                Appeal014Replay.Outcome.STALE_NOOP),
                        snapshot("stale-after-revision", Appeal014Replay.State.APPEAL_OPEN,
                                0, 0, 0, 1, 190, 1, CHARGED_BALANCES, NO_REFUNDS)));
    }

    private static Appeal014Replay.Snapshot snapshot(
            String scenarioId,
            Appeal014Replay.State state,
            long boundSerial,
            long boundRevision,
            long registrySerial,
            long registryRevision,
            long currentDay,
            int staleCount,
            Map<String, Long> balances,
            Map<String, Long> refunded) {
        return new Appeal014Replay.Snapshot(
                scenarioId, state, currentDay, boundSerial, boundRevision,
                registrySerial, registryRevision, 190, 0, staleCount, balances, refunded);
    }
}
