package com.xenoamess.kaishek.profile;

public enum ScopeType {
    ROOT, THIS, PREV, CHARACTER, TITLE, ORGANIZATION, PERFORMANCE_DOMAIN, PROVINCE, COUNTY,
    EVENT, CASE, DECISION, INTERACTION, ACTIVITY, WAR, ARMY, COUNCIL, CULTURE,
    ITERATOR, SAVED_SCOPE, SAVED, GLOBAL
}
